apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: myst-db
type: Opaque
data:
  # Base64 encoded values - these will be updated during deployment
  username: bXlzdGljc3RhcnM=  # mysticstars
  password: <BASE64_ENCODED_PASSWORD>  # Will be populated from Vault
  dbname: bXlzdGljc3RhcnM=  # mysticstars
  # Additional fields for backup configuration
  AWS_ACCESS_KEY_ID: <BASE64_ENCODED_AWS_ACCESS_KEY_ID>  # Will be populated from Vault
  AWS_SECRET_ACCESS_KEY: <BASE64_ENCODED_AWS_SECRET_ACCESS_KEY>  # Will be populated from Vault